### PR TITLE
Revert interact

### PR DESCRIPTION
**Pull request by jennan**
It looks like the issue with getting ipywidgets to work in a conda environment comes from the version packaged in the default channel. Using conda-forge to create the conda environment fixes this problem. This PR reverts PR #3 changes.

### CODE REVIEW

**Comment by jennan** [comment]
@pletzer please could you test this locally (you need to create a new conda environment) and on NeSI? Thank you :).

**Comment by pletzer** [comment]
Hi @jennan 

I'm getting this warning in 02.2 on my laptop in the env I created using the README.md instructions:

**Comment by pletzer** [comment]
Also in 02.2 on my laptop:
Screen Shot 2021-09-27 at 7 45 50 AM

**Comment by pletzer** [comment]
The sliders work great in 03.2 but there a warning at the bottom:

**Comment by pletzer** [comment]
I think we need to add pandas (lesson 6):

Screen Shot 2021-09-27 at 7 57 00 AM

**Pull request merged**
