### PR TITLE
Added Figure to RF Tutorial

### PR DESCRIPTION
**Pull request by prasys**
I've added a figure to the Random Forest tutorial to illustrate better on the big picture before we do the slider. 

Tested on : nesi999999991, gimkl-2018 kernel

### CODE REVIEW

**Comment by jennan** [comment]
Hi @prasys, thank you for adding this nice figure :).

Please could you commit the notebook without any content (clear all cells outputs)? this would make the repository lighter, ensure the learners start from a blank state and make reviewing the core changes easier :).

**Comment by prasys** [comment]
Hi @jennan - I've fixed it

Let me know if it is okay. I'll do for the validation bit - once I have done :)

**Comment by jennan** [comment]
Hi @prasys, please remove all the computed outputs of the notebook :-) (menu kernel / restart kernel and clear all outputs, so that it starts from a complete blank state.

**Comment by prasys** [comment]
I was doing from VSCode. Anyway I've cleared all the output now and it should be pretty good !!!

**Comment by jennan** [comment]
Thank you @prasys :).

**Pull request merged**
